### ISSUE TITLE
remove site.yml and 'site' tag

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-ansible#34]
We should remove `site.yml` and the site tag and the note in the README because folks should just do site specific things in another role (or even tasks in the playbook).  That's silly and strange to have a file in this role that you can change and don't commit?

**Comment by guimaluf** [comment]
I think there is no need for these dir/file. Any site specific thing would go outside this role.

This is a sort of thing that came in my mind while submitting the last PR. Apps repositories should be manage outside this role? or inside?  Since I'm basically getting a list of git repositories and calling the git module on it with a few customisations.
